//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment_Accounting.Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMC()
        {
            this.TaskTMC = new HashSet<TaskTMC>();
        }
        public string SizeUnit => $"{Size} {Unit.Name}";

        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTMC> TaskTMC { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
