//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment_Accounting.Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentWarehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentWarehouse()
        {
            this.EquipmentWarehouseClient = new HashSet<EquipmentWarehouseClient>();
            this.EquipmentWarehouseMaster = new HashSet<EquipmentWarehouseMaster>();
            this.EquipmentWarehouseS = new HashSet<EquipmentWarehouseS>();
            this.TaskEquipment = new HashSet<TaskEquipment>();
            this.TaskEquipmentC = new HashSet<TaskEquipmentC>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> EquipmentWarehouseTypeID { get; set; }
        public string SerialNum { get; set; }
        public Nullable<int> ConditionsID { get; set; }
        public string Model { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Conditions Conditions { get; set; }
        public virtual EquipmentWarehouseType EquipmentWarehouseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentWarehouseClient> EquipmentWarehouseClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentWarehouseMaster> EquipmentWarehouseMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentWarehouseS> EquipmentWarehouseS { get; set; }
        public virtual EquipmentWarehouseStatus EquipmentWarehouseStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskEquipment> TaskEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskEquipmentC> TaskEquipmentC { get; set; }
    }
}
