//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment_Accounting.Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Task = new HashSet<Task>();
            this.Client = new HashSet<Client>();
        }
        public string getFullName()
        {
            string modelName;
            if (Model != null)
                modelName = Model.Name;
            else modelName = "";
            string typeDevice;
            if (Type_Device != null)
                typeDevice = Type_Device.Name;
            else typeDevice = "";
            return $"{Name}|{IP}|{MAC}|{Serial_num}|{modelName}|{typeDevice}|{Address}";
        }
        public string FullName => getFullName();
        public int ID { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public string MAC { get; set; }
        public Nullable<int> Type_Device_id { get; set; }
        public Nullable<int> Conditions_id { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public Nullable<int> ID_in_item { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string SNMP { get; set; }
        public string Serial_num { get; set; }
        public string Num_vlan { get; set; }
        public Nullable<int> Brand_id { get; set; }
        public Nullable<int> Model_id { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Conditions Conditions { get; set; }
        public virtual Model Model { get; set; }
        public virtual Type_Device Type_Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
    }
}
