//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment_Accounting.Resource.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
        public DatabaseEntities(string con)
        : base(con)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientContracts> ClientContracts { get; set; }
        public virtual DbSet<Conditions> Conditions { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentWarehouse> EquipmentWarehouse { get; set; }
        public virtual DbSet<EquipmentWarehouseClient> EquipmentWarehouseClient { get; set; }
        public virtual DbSet<EquipmentWarehouseMaster> EquipmentWarehouseMaster { get; set; }
        public virtual DbSet<EquipmentWarehouseS> EquipmentWarehouseS { get; set; }
        public virtual DbSet<EquipmentWarehouseStatus> EquipmentWarehouseStatus { get; set; }
        public virtual DbSet<EquipmentWarehouseType> EquipmentWarehouseType { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<StatusTask> StatusTask { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskEquipment> TaskEquipment { get; set; }
        public virtual DbSet<TaskTMC> TaskTMC { get; set; }
        public virtual DbSet<TMC> TMC { get; set; }
        public virtual DbSet<Type_Device> Type_Device { get; set; }
        public virtual DbSet<TypeTask> TypeTask { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
