//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment_Accounting.Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskEquipment = new HashSet<TaskEquipment>();
            this.TaskTMC = new HashSet<TaskTMC>();
            this.TaskEquipmentC = new HashSet<TaskEquipmentC>();
        }
        public int DaysReturn()
        {
            if (StatusTaskID == 2) return 0;
            else return (int)((TimeSpan)(DateEnt - DateTime.Now)).TotalDays;
        }
        public int DaysEnd => (int)((TimeSpan)(DateEnt - DateTime.Now)).TotalDays;
        public string getID()
        {
            if (TypeID == 2) return $"ТТ-{IDofType}";
            else if (TypeID == 3) return $"ЗМС-{IDofType}";
            else if (TypeID == 4) return $"Д-{IDofType}";
            else return $"А-{IDofType}";
        }
        public string FullID => getID();

        public string getBackground()
        {
            if (StatusTaskID == 2) return "#696969";
            else if (DaysEnd < 0) return "#FA8072";
            else if (DaysEnd >= 0 && DaysEnd <= 3) return "#F0E68C";
            else return "#FFFFFF";
        }
        public string backRow => getBackground();
        public string dateS => string.Format("{0:dd/MM/yyyy}", DateStart);
        public string dateE => string.Format("{0:dd/MM/yyyy}", DateEnt);
        public int ID { get; set; }
        public int IDofType { get; set; }
        public Nullable<int> Contract { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnt { get; set; }
        public string Creator { get; set; }
        public Nullable<int> MasterID { get; set; }
        public Nullable<int> StatusTaskID { get; set; }
        public string Addres { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> PortID { get; set; }
        public string Note { get; set; }
    
        public virtual ClientContracts ClientContracts { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Logins Logins { get; set; }
        public virtual StatusTask StatusTask { get; set; }
        public virtual TypeTask TypeTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskEquipment> TaskEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTMC> TaskTMC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskEquipmentC> TaskEquipmentC { get; set; }
    }
}
